#User-service.yml file that defines my Kubernetes service for my user service microservice
apiVersion: v1
kind: Service
metadata:
  name: userservice-service
  labels:
    app: userservice
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: userservice
